### ISSUE TITLE
Dependency issue when updating to > Craft 3.6

### ISSUE THREAD

**Issue by romainpoirier** [enovatedesign/craft-style-inliner#9]
Update from Craft `3.5.1`9 to `3.6.2` using `composer update` returns a dependency error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - enovatedesign/craft-style-inliner 2.1.0 requires enshrined/svg-sanitize ^0.13.2 -> satisfiable by enshrined/svg-sanitize[0.13.3, 0.13.2].
    - enovatedesign/craft-style-inliner 2.1.0 requires enshrined/svg-sanitize ^0.13.2 -> satisfiable by enshrined/svg-sanitize[0.13.3, 0.13.2].
    - Can only install one of: enshrined/svg-sanitize[0.14.0, 0.13.2].
    - Can only install one of: enshrined/svg-sanitize[0.14.0, 0.13.3].
    - Can only install one of: enshrined/svg-sanitize[0.14.0, 0.13.3].
    - craftcms/cms 3.6.2 requires enshrined/svg-sanitize ~0.14.0 -> satisfiable by enshrined/svg-sanitize[0.14.0].
    - Installation request for craftcms/cms 3.6.2 -> satisfiable by craftcms/cms[3.6.2].
    - Installation request for enovatedesign/craft-style-inliner 2.1.0 -> satisfiable by enovatedesign/craft-style-inliner[2.1.0].
```

As long as the plugin `enovatedesign/craft-style-inliner` is setup in the composer.json file, the error blocks the update. Please can you fix this?

**Comment by mattsbanner** [comment]
Hi @romainpoirier 

What version do you have the plugin set to in your `composer.json` file?

If you change the version of `enovatedesign/craft-style-inliner` to `^2.0` or `2.2.0` and run `composer update` again this should resolve the issue. Craft also uses `svg-sanitize` under the hood so you will most likely need to update Craft and this plugin at the same time.

Please let me know how you get on.

**Comment by romainpoirier** [comment]
Sorry I forgot to mention that. I'm using the `2.1.0` version, and it seems to be the latest version under Craft `3.5.19` as there's no update showing for this plugin on the CP update page.

I tried to update to `2.2.0` from the composer.json file but still get an error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for enovatedesign/craft-style-inliner 2.2.0 -> satisfiable by enovatedesign/craft-style-inliner[2.2.0].
    - enovatedesign/craft-style-inliner 2.2.0 requires craftcms/cms ^3.6.0 -> satisfiable by craftcms/cms[3.6.0, 3.6.0-RC1, 3.6.0-RC2, 3.6.0-RC2.1, 3.6.0-RC3, 3.6.0-RC4, 3.6.0-beta.1, 3.6.0-beta.1.1, 3.6.0-beta.2, 3.6.0.1, 3.6.1, 3.6.2, 3.6.x-dev] but these conflict with your requirements or minimum-stability.
```

So I tried again, by updating simultaneously from Craft 3.5.19 to 3.6.2 + this plugin to 2.2.0 and that finally works! Thank you!
